#!/bin/bash
[[ -f .obsidian/workspace.json ]] || echo "Here is not a obsidian vault!"
base="$(dirname $0)"
find "$base/vault" -type f | xargs realpath --relative-base="$base/vault" | while read line; do
    mkdir -p "$(dirname $line)"
    ln -sf "$base/vault/$line" "$line"
done
